// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 03/02/2026, 23:25:14
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/molt/.openclaw/workspace/portfolio-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/molt/.openclaw/workspace/portfolio-site/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/molt/.openclaw/workspace/portfolio-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/molt/.openclaw/workspace/portfolio-site/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/molt/.openclaw/workspace/portfolio-site/plugins/**/*.{js,ts,mjs}","/home/molt/.openclaw/workspace/portfolio-site/composables/**/*.{js,ts,mjs}","/home/molt/.openclaw/workspace/portfolio-site/utils/**/*.{js,ts,mjs}","/home/molt/.openclaw/workspace/portfolio-site/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/molt/.openclaw/workspace/portfolio-site/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/molt/.openclaw/workspace/portfolio-site/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/molt/.openclaw/workspace/portfolio-site/app.config.{js,ts,mjs}"]}},
{"darkMode":"class","theme":{"extend":{"colors":{"primary":{"400":"#34d399","500":"#10b981","600":"#059669"}}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;